name: Your Guide to Canada
favicon: null
layout_spectrum: 0.4351890585385263
typography_spectrum: 0.29306356818415225
title: "The Newcomer's Guide to Canada"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.21226262371055782
  lightness: 0.5215050582773983
  saturation: 0.4219959736801684
  rhythmicContrast: 0.01904723048210144
purpose: []
