name: Your Guide to Canada
favicon: null
layout_spectrum: 0.99906
typography_spectrum: 0.8938
title: The Newcomer's Guide to Canada
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2b96c0'
    - '#800603'
    - '#194f7d'
    - '#000000'
  brandStrength: 0.21226262371055782
  lightness: 0.5625
  saturation: 0.4219959736801684
  rhythmicContrast: 0.5
purpose: []
